$ErrorActionPreference = 'Stop'
$repo = (Get-Location).Path
$reference = 'C:\Users\justin\.codex\plugins\cache\ghostworx-plugin-marketplace\swe-process\3.1.0\skills\swe-scaffold\references\solution'
$created = @('.codex/agents/codex/01-prompt-engineering-standards.md','.codex/agents/codex/02-openai-platform-notes.md','.codex/agents/codex/03-codex-extension-project-taxonomy.md','.codex/agents/codex/codex-engineer.toml','.codex/agents/swe/architecture-reviewer.toml','.codex/agents/swe/azure-db-developer.toml','.codex/agents/swe/azure-engineer.toml','.codex/agents/swe/code-commenter.toml','.codex/agents/swe/csharp-developer.toml','.codex/agents/swe/full-stack-developer.toml','.codex/agents/swe/integration-engineer.toml','.codex/agents/swe/maf-developer.toml','.codex/agents/swe/module-architect.toml','.codex/agents/swe/module-developer.toml','.codex/agents/swe/package-architect.toml','.codex/agents/swe/package-developer.toml','.codex/agents/swe/repo-author.toml','.codex/agents/swe/solution-architect.toml','.codex/agents/swe/solution-developer.toml','.codex/agents/swe/solution-validator.toml','.codex/agents/swe/test-runner.toml','.codex/agents/swe/ui-designer.toml','.codex/config.toml','AGENTS.md')
$skipped = @('.swe/changes/bugs/README.md','.swe/changes/enhancements/README.md','.swe/implementations/README.md','.swe/README.md','architecture/decisions/README.md','architecture/packages/README.md','architecture/README.md','architecture/views/systems/README.md','CONTEXT.md','README.md','VERSION.md')
$failures = [System.Collections.Generic.List[string]]::new(); $parity = 0
foreach ($rel in $created) { $dst=Join-Path $repo ($rel -replace '/', '\'); $src=Join-Path $reference ($rel -replace '/', '\'); if (!(Test-Path -LiteralPath $src -PathType Leaf)) { $failures.Add("missing reference: $rel"); continue }; if (!(Test-Path -LiteralPath $dst -PathType Leaf)) { $failures.Add("missing created file: $rel"); continue }; if ((Get-FileHash -LiteralPath $src -Algorithm SHA256).Hash -ne (Get-FileHash -LiteralPath $dst -Algorithm SHA256).Hash) { $failures.Add("byte mismatch: $rel") } else { $parity++ } }
foreach ($rel in $skipped) { $dst=Join-Path $repo ($rel -replace '/', '\'); if (!(Test-Path -LiteralPath $dst -PathType Leaf)) { $failures.Add("missing skipped file: $rel"); continue }; git diff --quiet -- $rel; if ($LASTEXITCODE -ne 0) { $failures.Add("skipped file has diff: $rel") }; if (!(git ls-files --error-unmatch -- $rel 2>$null)) { $failures.Add("skipped file is not tracked/pre-existing: $rel") } }
$sourceDirs = Get-ChildItem -LiteralPath $reference -Recurse -Force -Directory | ForEach-Object { $_.FullName.Substring($reference.Length + 1) }; foreach ($rel in $sourceDirs) { if (!(Test-Path -LiteralPath (Join-Path $repo ($rel -replace '/', '\')) -PathType Container)) { $failures.Add("missing required directory: $rel") } }
$config=Get-Content -Raw (Join-Path $repo '.codex/config.toml'); $sections=[regex]::Matches($config,'(?m)^\[agents\.([^\]]+)\]') | ForEach-Object { $_.Groups[1].Value }; if ($sections -notcontains 'test_runner' -or $sections -notcontains 'solution_validator') { $failures.Add('registry missing test_runner or solution_validator') }; foreach ($name in $sections) { $pattern = '(?ms)^\[agents\.' + [regex]::Escape($name) + '\].*?^config_file\s*=\s*"([^"]+)"'; $m=[regex]::Match($config,$pattern); if (!$m.Success -or !(Test-Path -LiteralPath (Join-Path $repo ('.codex/' + $m.Groups[1].Value)))) { $failures.Add("registry target missing: $name") } }
$runner=Get-Content -Raw (Join-Path $repo '.codex/agents/swe/test-runner.toml'); if ($runner -notmatch '(?m)^model\s*=\s*"gpt-5\.6-luna"' -or $runner -notmatch '(?m)^model_reasoning_effort\s*=\s*"medium"') { $failures.Add('test-runner model/effort mismatch') }; if (Get-ChildItem -LiteralPath $repo -Recurse -Force -File -Filter '.swe-scaffold-*' -ErrorAction SilentlyContinue) { $failures.Add('temporary .swe-scaffold-* files present') }; git diff --check; if ($LASTEXITCODE -ne 0) { $failures.Add('git diff --check failed') }
$status=if($failures.Count -eq 0){'Passed'}else{'Failed'}; Write-Output "status=$status created_byte_parity=$parity/$($created.Count) skipped_verified=$($skipped.Count) registry_agents=$($sections.Count) required_reference_dirs=$($sourceDirs.Count) failures=$($failures.Count)"; $failures | ForEach-Object { Write-Output "FAIL: $_" }; if($failures.Count -gt 0){exit 1}
