<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ghostagram.Core\Ghostagram.Core.csproj" />
    <ProjectReference Include="..\..\..\ghostworx-system\src\Ghostworx.System.Core\Ghostworx.System.Core.csproj" AdditionalProperties="Configuration=$(Configuration)" SetConfiguration="Configuration=$(Configuration)" />
    <ProjectReference Include="..\..\..\ghostworx-system\src\Ghostworx.System.Graph.Runtime\Ghostworx.System.Graph.Runtime.csproj" AdditionalProperties="Configuration=$(Configuration)" SetConfiguration="Configuration=$(Configuration)" />
    <ProjectReference Include="..\..\..\ghostworx-system\src\Ghostworx.System.Graph.Serialization\Ghostworx.System.Graph.Serialization.csproj" AdditionalProperties="Configuration=$(Configuration)" SetConfiguration="Configuration=$(Configuration)" />
  </ItemGroup>
</Project>
